# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("Cuba"); Pkg.test("Cuba"; coverage=true)'
# - julia -e 'cd(Pkg.dir("Cuba")); include("test/benchmark.jl")'
after_success:
 - julia -e 'cd(Pkg.dir("Cuba")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
